e_com/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from . import forms

app_name='accounts'

urlpatterns = [
    path('login/', views.MyLoginView.as_view(authentication_form=forms.MyAuthenticationForm), name='login'),
    path('register/', views.signup, name='sign_up'),
    path('profile/edit', views.EditProfileInformationView.as_view(), name='edit'),
    path('password_change/', auth_views.PasswordChangeView.as_view(form_class=forms.PwdChangeForm), name='password_change')
]

e_com/e_com/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_site.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

e_com/templates/includes/footer.html
<footer class='text-center'>

<div class="py-3" id='footer-top'>
    <a href="#" target="_blank">
    <i class="fab fa-facebook-f mr-3"></i>
    </a>

    <a href="#" target="_blank">
    <i class="fab fa-twitter mr-3"></i>
    </a>

    <a href="#" target="_blank">
    <i class="fab fa-youtube mr-3"></i>
    </a>

    <a href="#" target="_blank">
    <i class="fab fa-google-plus-g mr-3"></i>
    </a>

    <a href="https://github.com/mharre" target="_blank">
    <i class="fab fa-github mr-3"></i>
    </a>

</div>


<div class="footer-copyright py-3">
    © 2021 Copyright - This website is completely ficticious and is for development practice only
</div>

</footer>

e_com/templates/includes/nav_bar.html
{% load cart_template_tag %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'navbar.css' %}">
{% endblock %}

<header>
    <nav class="navbar navbar-expand-lg shadow rounded" id='main-nav'>
      <div class="container">
        <a class="navbar-brand" href="/">
          <strong id="brand">MHe-commerce</strong>
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'all_products' school='all' %}">Browse</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:sign_up' %}">Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% else %}
            <li class='nav-item'>
              <a href="{% url 'order_summary' %}" class="nav-link">
                  <span class="badge bg-danger z-depth-1 mr-1">{{ request.user|cart_item_count }}</span>
                  <i class="fas fa-shopping-cart"> </i>
                  <span class="clearfix d-none d-sm-inline-block"> Cart </span>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Profile<small>({{request.user}})</small>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'my_orders' %}">My Orders</a>
                <a class="dropdown-item" href="{% url 'accounts:edit' %}">Edit Profile</a>
                <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change Password</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% endif %}
          </ul>

          
          <!-- <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search.." aria-label="Search">
            <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
          </form> -->
        </div>
      </div>
    </nav>
</header>