e_com/e_com/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_site.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

e_com/my_site/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.StartingPageView.as_view(), name='starting_page'),
    path('products/<str:school>/', views.AllProductView.as_view(), name='all_products'),
    path('product/<slug>/', views.ProductDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add_to_cart'),
    path('add-coupon/', views.AddCouponView.as_view(), name='add_coupon'),
    path('add_single_item_to_cart/<slug>/', views.add_single_item_to_cart, name='add_single_item_to_cart'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='order_summary'),
    path('remove-from-cart/<slug>', views.remove_from_cart, name='remove_from_cart'),
    path('remove-item-from-cart/<slug>/', views.remove_single_item_from_cart, name='remove_single_item_from_cart'),
    path('checkout/', views.CheckOutView.as_view(), name='checkout'),
    path('payment/<payment_option>/', views.PaymentView.as_view(), name='payment'),
    path('request-refund/', views.RequestRefundView.as_view(), name='request_refund'),
    path('my-orders/', views.MyOrdersView.as_view(), name='my_orders'),
    path('search/', views.product_search, name='product_search')
]

e_com/my_site/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

from .models import Review, ShoppingCartOrderItem, Product

PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'Paypal')
)

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    ))
    last_name = forms.CharField(max_length=30, widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    ))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control'
        }
    ))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].label = 'Password'
        self.fields['password2'].label = 'Password Confirmation'
        self.fields['first_name'].label = 'First Name'
        self.fields['last_name'].label = 'Last Name'

        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None

        self.fields['password1'].widget = forms.widgets.PasswordInput(attrs={
            'class': 'form-control'
        })
        self.fields['password2'].widget = forms.widgets.PasswordInput(attrs={
            'class': 'form-control'
        })

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2' )
        help_texts = {
            'username': None,
        }
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            )
        }


class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='Choose...').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100'
        }))
    shipping_zip = forms.CharField(required=False)

    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label='Choose...').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100'
        }))
    billing_zip = forms.CharField(required=False)

    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo Code',
        'aria-label': "Recipient's username",
        'aria-describedby': "basic-addon2"
    }))


class RefundForm(forms.Form):
    ref_code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'rows': 4
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control'
    }))
    

class ReviewForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(ReviewForm, self).__init__(*args, **kwargs)
        ordered_product_ids = ShoppingCartOrderItem.objects.filter(user=user, ordered=True).values_list('item_id', flat=True)

        self.fields['product'].queryset = Product.objects.filter(id__in=ordered_product_ids)

    class Meta:
        model = Review
        exclude = ['user', 'date']
        widgets = {
            'product': forms.Select(attrs={
                'class': 'form-control'
            }),
            'rating': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': '5.0....'
            }),
            'comment': forms.Textarea(attrs={
                'class': 'form-control'
            })
        }
        error_messages = {
            'rating': {
                'max_digits': 'Please ensure that the rating is a decimal number and only 2 digits long',
                'max_whole_digits': 'Please ensure that the rating is a decimal number with only 1 digit before the decimal point'
            },
            'comment': {
                'min_length': 'Please ensure your comment has at least %(limit_value)d characters (it has %(show_value)d)'
            }
        }
    

class ProductSearchForm(forms.Form):
    q = forms.CharField()      

        
    
   

e_com/my_site/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone

from .forms import SignUpForm, CheckoutForm, CouponForm, RefundForm, ReviewForm, ProductSearchForm

from .models import Product, ShoppingCartOrder, ShoppingCartOrderItem, Address, Payment, Coupon, Refund, Review

import random
import string
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


def create_ref_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=20))


class StartingPageView(ListView):
    template_name = 'my_site/index.html'
    model = Product
    ordering = ['id']
    context_object_name = 'products'

    def get_queryset(self):
        base_query = super().get_queryset()
        data = base_query[:5]
        return data


class AllProductView(ListView):
    template_name = 'my_site/all_products.html'
    model = Product
    ordering=['id']
    paginate_by = 9
    context_object_name = 'all_products'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        fltr = self.kwargs['school']
        if fltr != 'all':
            qs = qs.filter(school=self.kwargs['school'])
        return qs


class ProductDetailView(DetailView):
    model = Product
    template_name = 'my_site/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = context['object']
        reviews = Review.objects.filter(product=product)
        context['reviews'] = reviews
        return context
     
    
class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            order = ShoppingCartOrder.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(request, 'my_site/order_summary.html', context)
        except ObjectDoesNotExist:
            messages.warning(request,'You do not have an active order')
            return redirect('all_products', school='all')


def is_valid_form(values):
    valid = True
    for field in values:
        if field == '':
            valid = False
    return valid


class CheckOutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            order = ShoppingCartOrder.objects.get(user=request.user, ordered=False)
            form = CheckoutForm()
            context = {
                'form': form,
                'couponform': CouponForm(),
                'order': order,
                'DISPLAY_COUPON_FORM': True
            }

            shipping_address_qs = Address.objects.filter(
                user=request.user, 
                address_type='S', 
                default=True)
            if shipping_address_qs.exists():
                context.update({
                    'default_shipping_address': shipping_address_qs[0]
                })

            billing_address_qs = Address.objects.filter(
                user=request.user, 
                address_type='B', 
                default=True)
            if billing_address_qs.exists():
                context.update({
                    'default_billing_address': billing_address_qs[0]
                })

            return render(request, 'my_site/checkout.html', context)
        except ObjectDoesNotExist:
            messages.info(request,'You do not have an active order')
            return redirect('checkout')
        

    def post(self, request, *args, **kwargs):
        form = CheckoutForm(request.POST or None)

        try:
            order = ShoppingCartOrder.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():

                use_default_shipping = form.cleaned_data.get('use_default_shipping')
                if use_default_shipping:
                    print('using default data')
                    address_qs = Address.objects.filter(
                    user=request.user, 
                    address_type='S', 
                    default=True)
                    if address_qs.exists():
                        shipping_address = address_qs[0]
                        order.shipping_address = shipping_address
                        order.save()
                    else:
                        messages.info(request, 'No default shipping address available')
                        return redirect(request,'checkout')
                else:
                    print('user is entering a new shipping address')

                    shipping_address = form.cleaned_data.get('shipping_address')
                    shipping_address2 = form.cleaned_data.get('shipping_address2')
                    shipping_country = form.cleaned_data.get('shipping_country')
                    shipping_zip = form.cleaned_data.get('shipping_zip')

                    if is_valid_form([shipping_address, shipping_country, shipping_zip]):
                        shipping_address = Address(
                            user = self.request.user,
                            street_address = shipping_address,
                            apartment = shipping_address2,
                            country = shipping_country,
                            zip_code = shipping_zip,
                            address_type = 'S'
                        )
                        shipping_address.save()

                        order.shipping_address = shipping_address
                        order.save()

                        set_default_shipping = form.cleaned_data.get('set_default_shipping')
                        if set_default_shipping:
                            shipping_address.default = True
                            shipping_address.save()
                    else:
                        messages.info(request, 'Please fill in the required shipping address fields')

                use_default_billing = form.cleaned_data.get('use_default_billing')
                same_billing_address = form.cleaned_data.get('same_billing_address')

                if same_billing_address:
                    billing_address = shipping_address
                    billing_address.pk = None
                    billing_address.save()
                    billing_address.address_type = 'B'
                    billing_address.save()
                    order.billing_address = billing_address
                    order.save()

                elif use_default_billing:
                    print('using default data')
                    address_qs = Address.objects.filter(
                    user=request.user, 
                    address_type='B', 
                    default=True)
                    if address_qs.exists():
                        billing_address = address_qs[0]
                        order.billing_address = billing_address
                        order.save()
                    else:
                        messages.info(request, 'No default billing address available')
                        return redirect(request,'checkout')
                else:
                    print('user is entering a new billing address')

                    billing_address = form.cleaned_data.get('billing_address')
                    billing_address2 = form.cleaned_data.get('billing_address2')
                    billing_country = form.cleaned_data.get('billing_country')
                    billing_zip = form.cleaned_data.get('billing_zip')

                    if is_valid_form([billing_address, billing_country, billing_zip]):
                        billing_address = Address(
                            user = self.request.user,
                            street_address = billing_address,
                            apartment = billing_address2,
                            country = billing_country,
                            zip_code = billing_zip,
                            address_type = 'B'
                        )
                        billing_address.save()
                        
                        order.billing_address = billing_address
                        order.save()

                        set_default_billing = form.cleaned_data.get('set_default_billing')
                        if set_default_billing:
                            billing_address.default = True
                            billing_address.save()
                    else:
                        messages.info(request, 'Please fill in the required billing address fields')    


                payment_option = form.cleaned_data.get('payment_option')
                
                if payment_option == 'S':
                    return redirect('payment', payment_option='stripe')
                elif payment_option == 'P':
                    return redirect('payment', payment_option='paypal')
                else:
                    messages.warning(request, 'Invalid payment option selected')
                    return redirect('checkout')
        except ObjectDoesNotExist:
            messages.warning(request,'You do not have an active order')

e_com/my_site/templates/my_site/all_products.html
{% extends 'base.html' %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'my_site/all_products.css' %}">
{% endblock %}

{% block title %}
MHe-commerce | Our Amazing Products
{% endblock %}

{% block content %}
<section id='product_list'>
<div id='wrapper'> 
    <div class="container-fluid w-75">
        <div class='row p-3'>
            <div class="container mt-3">
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark mt-3 shadow rounded" id='nav1'>

                    <span class="navbar-brand">School of:</span>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="basicExampleNav">

                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'all_products' school='all' %}">All
                        </a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'all_products' school='France' %}">France</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'all_products' school='Italy' %}">Italy</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'all_products' school='Russia' %}">Russia</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'all_products' school='Netherlands' %}">Netherlands</a>
                            </li>
            
                    </ul>

                    <form class="form-inline" action="/search/" method="GET">
                        <div class="md-form my-0">
                        <input class="form-control mr-sm-2" id='id_q' type="search" name='q' placeholder="Search.." aria-label="Search" required>
                        </div>
                    </form>
                    </div>
            </div>
        </div>
        <div class="card-deck">
        {% for product in all_products %}
            <div class="col-sm-4 mb-4">
                <div class="card h-100">
                    <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
                    <div class="card-body d-flex flex-column">
                    <h5 class="card-title">{{ product.name|title }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">${{ product.price }}</h6>
                    <p class="card-text">{{ product.history }}</p>
                    <a href="{{ product.get_absolute_url }}" class="btn mt-auto" id='btn'>More Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
    
    <div class="pagination justify-content-center pt-3">
      <nav aria-label='pagination'>
          <ul class="pagination step-links">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label='Previous'>
                        <span aria-hidden='true'>&laquo;</span>
                    </a>
                </li>
            {% endif %}

            <li class="page-item">
                <a class='page-link'>
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </a>
            </li>

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label='Next'>
                        <span aria-hidden='true'> &raquo; </span>
                    </a>
                </li>
            {% endif %}
            </ul>
      </nav>
    </div>

  </div>
</div>

</section>
{% endblock %}

e_com/my_site/templates/my_site/checkout.html
{% extends 'base.html' %}

{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'my_site/checkout.css' %}">
{% endblock %}

{% block title %}
Checkout or browse for more! | MHe-commerce 
{% endblock %}

{% block content %}

<main >
<div class="container-fluid" id='checkout-wrapper'>
  <div class="container parent1">
    <h2 class="py-5 h2 text-center">Checkout</h2>
    <div class="row">
      <div class="col-md-8 mb-4">
        <div class="card shadow bg-white rounded">
          <form method="POST" class="card-body">
            {% csrf_token %}

            <h3>Shipping address</h3>

            <div class='hideable_shipping_form'>

              <div class="md-form mb-5">
                <label for="shipping_address" class="text-muted">Address</label>
                <input type='text' placeholder='1234 Main St..' id='shipping_address' name='shipping_address' class='form-control' />
              </div>

              <div class="md-form mb-5">
                <label for="shipping_address2" class="text-muted">Address 2 (optional)</label>
                <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
              </div>

              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.shipping_country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="shipping_zip">Zip</label>
                  <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>
              </div>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same_billing_address">
                <label class="custom-control-label" for="same_billing_address">Billing address is the same as my shipping address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
              </div>

            </div>

            {% if default_shipping_address %}
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
              <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:20 }}</label>
            </div>
            {% endif %}

            <hr>

            <h3>Billing address</h3>

            <div class='hideable_billing_form'>
              <div class="md-form mb-5">
                <label for="billing_address" class="text-muted">Address</label>
                <input type='text' placeholder='1234 Main St' id='billing_address' name='billing_address' class='form-control' />
                
              </div>

              <div class="md-form mb-5">
                <label for="billing_address2" class="text-muted">Address 2 (optional)</label>
                <input type='text' placeholder='Apartment or suite' id='billing_address2' name='billing_address2' class='form-control' />
                
              </div>

              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country" class='text-muted'>Country</label>
                  {{ form.billing_country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>

                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="billing_zip" class='text-muted'>Zip</label>
                  <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip' class='form-control' />
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>

              </div>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
                <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
              </div>

            </div>

            {% if default_billing_address %}
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing">
              <label class="custom-control-label" for="use_default_billing">Use default billing address: {{ default_billing_address.street_address|truncatechars:20 }}</label>
            </div>
            {% endif %}
            <hr>

            <h3>Payment option</h3>

            <div class="d-block my-3">
              {% for value, name in form.fields.payment_option.choices %}
              <div class="custom-control custom-radio">
                <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
              </div>
              {% endfor %}
            </div>

            <hr class="mb-4">
            <button class="btn btn-lg btn-block" id='continue-btn' type="submit">Continue to checkout</button>

          </form>

        </div>

      </div>

      <div class="col-md-4 mb-4">
        {% include "my_site/order_snippet.html" %}
      </div>

    </div>

  </div>
</div>
</main>

{% endblock %}

{% block extra_scripts %}
<script>
var hideable_shipping_form = $('.hideable_shipping_form');
var hideable_billing_form = $('.hideable_billing_form');

var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
var use_default_billing = document.querySelector("input[name=use_default_billing]");

use_default_shipping.addEventListener('change', function() {
  if (this.checked) {
    hideable_shipping_form.hide();
  } else {
    hideable_shipping_form.show();
  }
})

use_default_billing.addEventListener('change', function() {
  if (this.checked) {
    hideable_billing_form.hide();
  } else {
    hideable_billing_form.show();
  }
})
  
</script>
{% endblock %}

e_com/my_site/templates/my_site/my_orders.html
{% extends 'base.html' %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'my_site/my_orders.css' %}">
{% endblock %}

{% block content %}
<div class="container-fluid" id='myorders-wrapper'>

    <div class="jumbotron jumbotron-fluid">
        <div class="container text-center">
        <h1 class="display-4">Your Orders</h1>
        </div>
    </div>
    {% if object %}
    <div class="row justify-content-center">
        {% for order in object %}
        {% for order_item in order.items.all %}
        <div class="col-sm-4">
            <div class="card my-3 shadow bg-rounded">
            <img src="{{ order_item.item.image.url }}" class="card-img-top shadow bg-rounded" alt="{{ order_item.item }} ">
            <div class="card-header text-center">
                <h6><strong>{{ order_item.item.name }}</strong></h6>
            </div>
            <div class="card-body flex-column text-center">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Ordered On: {{ order.ordered_date }}</li>
                    <li class="list-group-item">Price: ${{ order_item.item.price }}</li>
                    <li class="list-group-item">Reference Code: {{ order.ref_code }}</li>
                    <li class="list-group-item">Request Refund: <a href="{% url 'request_refund' %}" class='btn' id='refund-button'><i class="fas fa-random"></i></a></li>
                  </ul>
            </div>
            </div>
        </div>
        {% endfor %}
        {% endfor %}
    </div>
    <div class="container text-center">
        <button class="btn btn-sm" id='review'>Leave a review?</button>
    </div>

    <div class="container w-25 pb-5">
        <div class="container-fluid" id="wrapper">
            <form method="POST" id='form1'>
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group px-3 my-3 {% if field.errors %}invalid{% endif %}">
                {{ field.label_tag }}
                {{ field }}
                {{ field.help_text }}
                {{ field.errors }}
                </div>
                {% endfor %}
                <button type="submit" id='review-submit' class="btn ml-3">Submit</button>
            </form>
        </div>
    </div>
    {% else %}
    <div class="container parent1 text-center" id='no-orders'>
        <h1>You don't have any orders</h1>
        <h3>Click <a href="{% url 'all_products' school='all' %}">here</a> to view our products!</h3>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block extra_scripts %}
<script type='text/javascript'>
$( document ).ready( function() {
    $( "#review" ).click( function() {
        $( "#form1" ).toggle(1000);
    });
});
</script>
{% endblock %}

e_com/my_site/templates/my_site/request_refund.html
{% extends 'base.html' %}

{% block title %}
Request a Refund 
{% endblock %}

{% block content %}
<div class="container-fluid" id='refund-wrapper'>
    <div class="container parent1 h-100 d-flex justify-content-center align-items-center"> 
        <div class="container w-50 py-3" id='refund-form-wrapper'>
            <h2 class='text-center'>Request Refund</h2>
            <form method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class='btn btn-primary btn-block mt-3' id='refund-submit-btn'>Submit</button>
            </form>
        </div>
    </div>

</div>
{% endblock %}